### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by drbytes** [flo199213/Hoverboard-Firmware-Hack-Gen2#1]
I've managed to flash the two boards from a eslide 650 with this.
Had to unlock the firmware first on both boards and solder a header. My boards have a different layout. This is the first time working with STLINK/STM32, 0 prior experience but flashing with the keil sdk went well, just keep holding the power button or it doesn't work. Good job on this firmware, I'll see if I can get it to interface with a pi this weekend.
Is the work on this ongoing?

**Comment by gaucho1978** [comment]
I'll try the same. Is it a way to restore the hoverboard after playing with this hack?
